# Copyright (c) 2023, Bennett Samowich <bennett@foolean.org>
# All rights reserved
# SPDX short identifier: BSD-3-Clause
###############################################################################
#
# playbook: os.yml
#
#   Ansible playbook for common operating system configuration
#
###############################################################################
---


# Ensure that the nodes are available
# Useful if we're being run from an automation
# tool such as Packer or Terraform
- name: Wait until the systems are available
  hosts: all
  gather_facts: false # important
  tasks:
    - name: Wait for system to become reachable
      ansible.builtin.wait_for_connection:
        timeout: 300


# Ensure that any uncommitted changes in /etc
# are committed before we start doing anything
- name: Run etckeeper pre-commit
  hosts: all
  gather_facts: false
  tasks:
    - name: Run etckeeper pre-commit
      ansible.builtin.import_tasks:
        file: "{{ ansible_config_file | dirname }}/roles/foolean/etckeeper/tasks/pre-commit.yml"
      when: not ansible_check_mode


- name: Playbook for baseline OS configuration
  hosts: all
  roles:
    # Set RedHat subscriptions
    - role: foolean/redhat
    # Install and configure etckeeper to track changes
    - role: foolean/etckeeper
      tags: [foolean_etckeeper]
    - role: foolean/autofs
    - role: foolean/banner
    - role: foolean/chrony
    - role: foolean/cramfs
    - role: foolean/squashfs
    - role: foolean/udf
    - role: foolean/usb
    - role: foolean/mounts
    - role: foolean/selinux
    - role: foolean/sysctl
    - role: foolean/systemd
    - role: foolean/xinetd
    - role: foolean/xserver
    - role: foolean/avahi
    - role: foolean/cups
    - role: foolean/dhcp
    - role: foolean/dns
    - role: foolean/ftp
    - role: foolean/tftp
    - role: foolean/proftp
    - role: foolean/apache2
    - role: foolean/nginx
    - role: foolean/dovecot
    - role: foolean/cyrusimap
    - role: foolean/samba
    - role: foolean/snmp
    - role: foolean/rsync
    - role: foolean/nfs
    - role: foolean/postfix
    - role: foolean/rsh
    - role: foolean/talk
    - role: foolean/telnet
    - role: foolean/ldap
    - role: foolean/network


# Ensure that any uncommitted changes in /etc
# are committed now that we have finished
- name: Run etckeeper post-commit
  hosts: all
  gather_facts: false
  tasks:
    - name: Run etckeeper post-commit
      ansible.builtin.import_tasks:
        file: '{{ ansible_config_file | dirname }}/roles/foolean/etckeeper/tasks/post-commit.yml'
      when: not ansible_check_mode
